/*
* generated by Xtext
*/
package ca.queensu.cs.mase.ui.contentassist;

import ca.queensu.cs.mase.ui.contentassist.AbstractUrmlProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class UrmlProposalProvider extends AbstractUrmlProposalProvider {

}
