/*
* generated by Xtext
*/
package ca.queensu.cs.mase.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

import ca.queensu.cs.mase.urml.ActionCode;
import ca.queensu.cs.mase.urml.Operation;

/**
 * customization of the default outline structure
 * 
 */
public class UrmlOutlineTreeProvider extends DefaultOutlineTreeProvider {
	protected boolean _isLeaf(ActionCode ac) {
		return true;
	}
	
	protected boolean _isLeaf(Operation op) {
		return true;
	}
}
