/*
* generated by Xtext
*/
package ca.queensu.cs.mase;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class UrmlUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return ca.queensu.cs.mase.ui.internal.UrmlActivator.getInstance().getInjector("ca.queensu.cs.mase.Urml");
	}
	
}
