/*
 * generated by Xtext
 */
package ca.queensu.cs.mase.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import ca.queensu.cs.mase.ui.internal.UrmlActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class UrmlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return UrmlActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return UrmlActivator.getInstance().getInjector(UrmlActivator.CA_QUEENSU_CS_MASE_URML);
	}
	
}
