/*
 * generated by Xtext
 */
package ca.queensu.cs.mase;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class UrmlRuntimeModule extends ca.queensu.cs.mase.AbstractUrmlRuntimeModule {

}
