/*
* generated by Xtext
*/
package ca.queensu.cs.mase.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import ca.queensu.cs.mase.services.UrmlGrammarAccess;

public class UrmlParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private UrmlGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected ca.queensu.cs.mase.parser.antlr.internal.InternalUrmlParser createParser(XtextTokenStream stream) {
		return new ca.queensu.cs.mase.parser.antlr.internal.InternalUrmlParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public UrmlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(UrmlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
