/*
* generated by Xtext
*/
package ca.queensu.cs.mase.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class UrmlAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("ca/queensu/cs/mase/parser/antlr/internal/InternalUrml.tokens");
	}
}
